version: 2.1

orbs:
  windows: circleci/windows@2.4.1

jobs:
  test:
    description: Setup and run unit tests
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Run Unit Tests"
          command: dotnet.exe test --logger "trx" --results-directory "TestResults"
      - run:
          name: "Run Test Coverage"
          command: |
              dotnet tool install JetBrains.dotCover.GlobalTool -g
              dotnet dotcover test --dcReportType=HTML --dcOutput=TestResults\coverage.html --no-build
      - run:
          name: "Upload Test Results"
          when: always
          command: |
              dotnet tool install -g trx2junit
              trx2junit TestResults/*.trx
      - store_test_results:
          path: TestResults
      - store_artifacts:
          path: TestResults
          destination: TestResults
  buildAndDeploy:
    description: Build and Deploy library with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - when:
            condition:
               equal: [main, << pipeline.git.branch >>]
            steps:
              - run:
                    name: Push to NuGet
                    command: |
                      dotnet pack --output artifacts --configuration Release /p:ContinuousIntegrationBuild=true
                      dotnet nuget push "**/*.nupkg" -s "https://api.nuget.org/v3/index.json" --api-key "$env:NUGET_API_KEY"
      - when:
            condition:
               not: 
                equal: [main, << pipeline.git.branch >>]
            steps:
              - run:
                  name: Build
                  command: dotnet build --configuration Release /p:ContinuousIntegrationBuild=true 

workflows:
  test_and_build:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - gh-pages
      - buildAndDeploy:
          filters:
            branches:
              ignore:
                - gh-pages
          requires:
            - test