version: 2.1

orbs:
  windows: circleci/windows@4.1.1

jobs:
  test:
    description: Setup and run unit tests
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:9.0
    steps:
      - checkout
      - run: 
          name: "Setup Path Variable"
          command: |          
            echo 'export PATH="$PATH:/root/.dotnet/tools"' >> $BASH_ENV
      - run:
          name: "Run Unit Tests"
          command: dotnet test --results-directory "TestResults" --logger "trx;LogFileName=results.trx" --collect:"XPlat Code Coverage" 
      - run:
          name: "Upload Test Results"
          when: always
          command: |
              dotnet tool install -g trx2junit
              trx2junit TestResults/results.trx
      - store_test_results:
          path: TestResults/results.xml
      - store_artifacts:
          path: TestResults
          destination: TestResults
  buildAndDeploy:
    description: Build and Deploy library with Release configuration
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:9.0
    steps:
      - checkout
      - run: 
          name: "Setup Path Variable"
          command: |          
            echo 'export PATH="$PATH:/root/.dotnet/tools"' >> $BASH_ENV
      - when:
            condition:
               equal: [main, << pipeline.git.branch >>]
            steps:
              - run:
                    name: Push to NuGet
                    command: |
                      dotnet pack --output artifacts --configuration Release /p:ContinuousIntegrationBuild=true
                      dotnet nuget push "**/*.nupkg" -s "https://api.nuget.org/v3/index.json" --api-key "$NUGET_API_KEY"
      - when:
            condition:
               not: 
                equal: [main, << pipeline.git.branch >>]
            steps:
              - run:
                  name: Build
                  command: dotnet build --configuration Release /p:ContinuousIntegrationBuild=true 

workflows:
  test_and_build:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - gh-pages
      - buildAndDeploy:
          filters:
            branches:
              ignore:
                - gh-pages
          requires:
            - test