version: 2.1

orbs:
  windows: circleci/windows@2.4.1

jobs:
  BuildAndTest:
    description: Build and Test
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet.exe build --configuration Release /p:ContinuousIntegrationBuild=true
      - run:
          name: "Run Unit Tests"
          command: dotnet.exe test --logger "trx" --results-directory "TestResults" --no-build
      - run:
          name: "Run Test Coverage"
          command: |
              dotnet tool install JetBrains.dotCover.GlobalTool -g
              dotnet dotcover test --dcReportType=XML --dcOutput=TestResults\coverage.xml --no-build
      - run:
          name: "Upload Test Results"
          when: always
          command: |
              dotnet tool install -g trx2junit
              trx2junit TestResults/*.trx
      - store_test_results:
          path: TestResults
      - store_artifacts:
          path: TestResults
          destination: TestResults
  deploy:
    description: Deploy the package to NuGet. Only run on the main branch.
    executor:
        name: windows/default
    steps:
        - when:
            condition:
               equal: [main, << pipeline.git.branch >>]
            steps:
              - checkout
              - run:
                    name: Push to NuGet
                    command: |
                      dotnet pack --output artifacts --configuration Release
                      dotnet nuget push "artifacts/*.nupkg" -s "https://api.nuget.org/v3/index.json" -k $NUGET_API_KEY 
        - when:
            condition:
               not: 
                equal: [main, << pipeline.git.branch >>]
            steps:
              - run: echo "Skipping deploy."

workflows:
  test_and_build:
    jobs:
      - BuildAndTest
      - deploy:
          requires:
            - BuildAndTest 