version: 2.1

orbs:
  windows: circleci/windows@2.4.1

jobs:
  test:
    description: Setup and run unit tests
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Run Unit Tests"
          command: dotnet.exe test --logger "trx" --results-directory "..\TestResults"
      - run:
          name: test results
          when: always
          command: |
              dotnet tool install -g trx2junit
              trx2junit TestResults/*.trx
      - store_test_results:
          path: tests/TestResults
      - store_artifacts:
          path: tests/TestResults
          destination: TestResults
  build:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet.exe build --configuration Release /p:ContinuousIntegrationBuild=true
  deploy:
    description: Deploy the package to NuGet. Only run on the main branch.
    executor:
        name: windows/default
    steps:
        - when:
            condition:
               equal: [main, << pipeline.git.branch >>]
            steps:
              - checkout
              - run:
                    name: Push to NuGet
                    command: |
                      dotnet pack --output artifacts --configuration Release
                      dotnet nuget push artifacts/*.nupkg -k ${NUGET_API_KEY} -s ${NUGET_URL} 
        - when:
            condition:
               not: 
                equal: [main, << pipeline.git.branch >>]
            steps:
              - run: echo "Skipping deploy."


workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build 